# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Tour
  #   url: tour
  #   weight: 10
  # - name: News
  #   url: post
  #   weight: 20
  - name: People
    url: people
    weight: 30
  # - name: Events
  #   url: event
  #   weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Contact
    url: contact
    weight: 60
  - name: Short courses
    identifier: short-courses
    url: short_courses
    weight: 70
  - name: Past
    parent: short-courses
    url: short_courses/past
    weight: 10
  - name: Upcoming
    parent: short-courses
    url: short_courses/upcoming
    weight: 20
  - name: AIMSxImperial South Africa
    identifier: sa_aimsximperial2025
    url: sa_aimsximperial2025
    weight: 80
  - name: Overview
    parent: sa_aimsximperial2025
    url: sa_aimsximperial2025/overview/
    weight: 10
  - name: Application
    parent: sa_aimsximperial2025
    url: sa_aimsximperial2025/application/
    weight: 20
  - name: Programme
    parent: sa_aimsximperial2025
    url: sa_aimsximperial2025/programme/
    weight: 30
  - name: Lecturers
    parent: sa_aimsximperial2025
    url: sa_aimsximperial2025/lecturers/
    weight: 40
  - name: Past short courses
    parent: sa_aimsximperial2025
    url: /short_courses/past
    weight: 50
